## Taken from https://dev.to/petr7555/github-action-for-multi-project-rust-repository-28d5
## Thanks to https://dev.to/petr7555

name: Build

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build, test, clippy all
      run: sh -x ./scripts/ci.sh
